// Copyright StraySpark Studio 2026. All Rights Reserved.
//
// Phase D.3 — Test authoring & run.
//
// `create_automation_spec` writes a new .cpp Spec file under the project's
// Source/ tree. The file will compile and register a test only after a
// project rebuild — the tool's response makes that explicit.
//
// `run_automation_specs` drives the existing FAutomationTestFramework via the
// "Automation RunTests" console command. Tests are queued and executed by the
// engine's automation controller; results are accumulated in a static buffer
// and returned by `get_last_test_report`.
//
// `add_functional_test_actor` instantiates an AFunctionalTest in the editor
// world; placement-based functional testing is the lighter-weight alternative
// to writing C++ specs.

#include "Tools/MCPTestAuthoringTools.h"

#include "MCPToolRegistry.h"
#include "MCPToolBuilder.h"
#include "MCPProtocol.h"
#include "MCPValidate.h"

#include "Editor.h"
#include "Engine/World.h"
#include "EngineUtils.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "HAL/PlatformFileManager.h"
#include "HAL/PlatformProcess.h"
#include "Misc/App.h"

#include "Misc/AutomationTest.h"
#include "FunctionalTest.h"

namespace MCPTestAuthoringTools
{

// ---------------------------------------------------------------------------
// Last-report buffer
// ---------------------------------------------------------------------------
//
// We don't subscribe to the automation controller's full delegate chain
// (which runs async across multiple ticks). Instead we snapshot whatever the
// framework has accumulated when run_automation_specs returns. For the most
// recent invocation, get_last_test_report returns that snapshot.
//
// This is intentionally minimal: a richer integration would hook the
// IAutomationControllerModule events for per-it timings.

struct FLastReport
{
	bool bRan = false;
	FString Filter;
	int32 NumPass = 0;
	int32 NumFail = 0;
	double DurationSeconds = 0.0;
	TArray<TSharedPtr<FJsonValue>> Entries;
};

static FLastReport& GetLastReport()
{
	static FLastReport R;
	return R;
}

// ---------------------------------------------------------------------------
// Spec scaffolding
// ---------------------------------------------------------------------------

/** Produce the .cpp text for a UE Automation Spec with one passing 'It'. */
static FString BuildSpecBody(const FString& SpecName, const TArray<FString>& Tags, const FString& UserBody)
{
	FString FlagSuffix;
	if (Tags.Num() > 0)
	{
		// EAutomationTestFlags is a bitmask; default to EditorContext + EngineFilter so the
		// tests are picked up by the editor automation suite.
		FlagSuffix = TEXT(" | EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter | EAutomationTestFlags::ProductFilter");
	}

	FString Body;
	Body += TEXT("// Generated by UnrealMCPServer create_automation_spec. Edit freely.\n");
	Body += TEXT("\n");
	Body += TEXT("#include \"Misc/AutomationTest.h\"\n");
	Body += TEXT("\n");
	Body += FString::Printf(TEXT("BEGIN_DEFINE_SPEC(F%sSpec, \"UnrealMCP.%s\","), *SpecName, *SpecName);
	Body += TEXT("\n");
	Body += TEXT("    EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::EngineFilter)");
	Body += FlagSuffix;
	Body += TEXT("\n");
	Body += FString::Printf(TEXT("END_DEFINE_SPEC(F%sSpec)\n"), *SpecName);
	Body += TEXT("\n");
	Body += FString::Printf(TEXT("void F%sSpec::Define()\n{\n"), *SpecName);
	Body += FString::Printf(TEXT("    Describe(TEXT(\"%s\"), [this]()\n    {\n"), *SpecName);
	if (!UserBody.IsEmpty())
	{
		Body += UserBody;
		Body += TEXT("\n");
	}
	else
	{
		Body += TEXT("        It(TEXT(\"compiles and runs\"), [this]()\n");
		Body += TEXT("        {\n");
		Body += TEXT("            TestTrue(TEXT(\"placeholder\"), true);\n");
		Body += TEXT("        });\n");
	}
	Body += TEXT("    });\n}\n");
	return Body;
}

// ---------------------------------------------------------------------------

void RegisterAll(FMCPToolRegistry& Registry)
{
	// ================================================================
	// create_automation_spec
	// ================================================================
	MCP_TOOL(Registry, "create_automation_spec")
		.Description(TEXT(
			"Scaffold a UE Automation Spec .cpp under the project's Source/ tree. The file compiles "
			"into the project on the next build / Live Coding patch. Returns the absolute path written. "
			"Use list_automation_specs / run_automation_specs once the spec is registered."))
		.StringArg(TEXT("name"),
			TEXT("Spec name (PascalCase). Becomes class F<name>Spec and 'UnrealMCP.<name>' in the test catalogue."), true)
		.StringArrayArg(TEXT("tags"),
			TEXT("Optional tags appended into the test flags (e.g., 'EditorContext'). Default: EditorContext + EngineFilter."))
		.StringArg(TEXT("body"),
			TEXT("Optional custom Spec body inserted inside Describe(...) — should be raw C++ such as 'It(...)' calls. Defaults to a single passing assertion."))
		.StringArg(TEXT("target_dir"),
			TEXT("Subdirectory under <Project>/Source for the file (default 'MCPGenerated/Specs'). Created if missing."))
		.Handle([](const TSharedPtr<FJsonObject>& Args) -> FMCPToolResult
		{
			BAIL_IF_INVALID(FMCPValidate::Args(Args));

			FString Name;
			BAIL_IF_INVALID(FMCPValidate::RequiredString(Args, TEXT("name"), Name));
			BAIL_IF_INVALID(FMCPValidate::AssetName(Name));

			TArray<FString> Tags;
			const TArray<TSharedPtr<FJsonValue>>* TagsArr = nullptr;
			if (Args->TryGetArrayField(TEXT("tags"), TagsArr) && TagsArr)
			{
				for (const auto& V : *TagsArr) { FString S; if (V->TryGetString(S)) Tags.Add(S); }
			}

			FString UserBody;
			Args->TryGetStringField(TEXT("body"), UserBody);

			FString TargetDir = TEXT("MCPGenerated/Specs");
			Args->TryGetStringField(TEXT("target_dir"), TargetDir);

			FString FullDir = FPaths::ConvertRelativePathToFull(
				FPaths::ProjectDir() / TEXT("Source") / TargetDir);
			IPlatformFile& PF = FPlatformFileManager::Get().GetPlatformFile();
			if (!PF.DirectoryExists(*FullDir))
			{
				if (!PF.CreateDirectoryTree(*FullDir))
				{
					return FMCPToolResult::ErrorStructured(EMCPError::Internal,
						FString::Printf(TEXT("Could not create directory '%s'"), *FullDir));
				}
			}

			FString FullPath = FullDir / (Name + TEXT("Spec.cpp"));
			if (PF.FileExists(*FullPath))
			{
				return FMCPToolResult::ErrorStructured(EMCPError::AlreadyExists,
					FString::Printf(TEXT("Spec file already exists: %s"), *FullPath),
					TEXT("Pick a different name or delete the existing file first."));
			}

			FString Source = BuildSpecBody(Name, Tags, UserBody);
			if (!FFileHelper::SaveStringToFile(Source, *FullPath))
			{
				return FMCPToolResult::ErrorStructured(EMCPError::Internal,
					FString::Printf(TEXT("Failed to write '%s'"), *FullPath));
			}

			TSharedPtr<FJsonObject> R = MakeShared<FJsonObject>();
			R->SetStringField(TEXT("path"), FullPath);
			R->SetStringField(TEXT("class_name"), FString::Printf(TEXT("F%sSpec"), *Name));
			R->SetStringField(TEXT("test_name"), FString::Printf(TEXT("UnrealMCP.%s"), *Name));
			R->SetStringField(TEXT("hint"), TEXT("Recompile the project (Live Coding or full build) to register the test."));
			return FMCPToolResult::SuccessStructured(
				FString::Printf(TEXT("Spec written: %s"), *FullPath), R);
		});

	// ================================================================
	// list_automation_specs
	// ================================================================
	MCP_TOOL(Registry, "list_automation_specs")
		.Description(TEXT(
			"Enumerate registered automation tests known to FAutomationTestFramework. "
			"Filter by substring on the test name."))
		.ReadOnly()
		.Idempotent()
		.StringArg(TEXT("name_filter"), TEXT("Substring filter applied to the test name (case-insensitive)."))
		.Handle([](const TSharedPtr<FJsonObject>& Args) -> FMCPToolResult
		{
			BAIL_IF_INVALID(FMCPValidate::Args(Args));

			FString Filter;
			Args->TryGetStringField(TEXT("name_filter"), Filter);

			FAutomationTestFramework& Framework = FAutomationTestFramework::Get();
			// The framework's RequestedTestFilter defaults to SmokeFilter only,
			// which hides Engine/Product/Perf/Stress-filter tests (including our
			// own specs) from GetValidTestNames. Widen to all filter groups.
			Framework.SetRequestedTestFilter(EAutomationTestFlags_FilterMask);
			TArray<FAutomationTestInfo> All;
			Framework.GetValidTestNames(All);

			TArray<TSharedPtr<FJsonValue>> Items;
			for (const FAutomationTestInfo& Info : All)
			{
				const FString TestName = Info.GetDisplayName();
				if (!Filter.IsEmpty() && !TestName.Contains(Filter, ESearchCase::IgnoreCase)) continue;

				TSharedPtr<FJsonObject> E = MakeShared<FJsonObject>();
				E->SetStringField(TEXT("name"), TestName);
				E->SetStringField(TEXT("full_test_path"), Info.GetFullTestPath());
				E->SetStringField(TEXT("test_name"), Info.GetTestName());
				E->SetNumberField(TEXT("num_participants"), Info.GetNumParticipantsRequired());
				Items.Add(MakeShared<FJsonValueObject>(E));
			}

			TSharedPtr<FJsonObject> R = MakeShared<FJsonObject>();
			R->SetNumberField(TEXT("total"), Items.Num());
			R->SetArrayField(TEXT("specs"), Items);
			return FMCPToolResult::SuccessStructured(
				FString::Printf(TEXT("%d spec(s) found"), Items.Num()), R);
		});

	// ================================================================
	// run_automation_specs
	// ================================================================
	MCP_TOOL(Registry, "run_automation_specs")
        .Destructive() // General code execution can exceed Scene effects.
		.LongRunning()
		.Description(TEXT(
			"Run automation specs whose name contains the filter substring. Synchronous: blocks until the "
			"queued tests have completed (up to timeout_sec). Stores the result in the last-report buffer "
			"so get_last_test_report can fetch it again. Returns aggregate {pass, fail, duration_sec}."))
		.StringArg(TEXT("filter"), TEXT("Substring matched against test names. Empty matches all."))
		.IntArg(TEXT("timeout_sec"), TEXT("Maximum seconds to wait (default 60, max 600)."))
		.Handle([](const TSharedPtr<FJsonObject>& Args) -> FMCPToolResult
		{
			BAIL_IF_INVALID(FMCPValidate::Args(Args));

			FString Filter;
			Args->TryGetStringField(TEXT("filter"), Filter);

			int32 Timeout = 60;
			if (Args->HasField(TEXT("timeout_sec")))
			{
				Timeout = (int32)Args->GetNumberField(TEXT("timeout_sec"));
				BAIL_IF_INVALID(FMCPValidate::InRangeI(Timeout, 1, 600, TEXT("timeout_sec")));
			}

			FAutomationTestFramework& Framework = FAutomationTestFramework::Get();
			// See list_automation_specs: widen the default SmokeFilter-only view
			// so Engine/Product-filter specs can be found and run.
			Framework.SetRequestedTestFilter(EAutomationTestFlags_FilterMask);
			TArray<FAutomationTestInfo> All;
			Framework.GetValidTestNames(All);

			TArray<FAutomationTestInfo> Selected;
			for (const FAutomationTestInfo& Info : All)
			{
				if (Filter.IsEmpty() || Info.GetDisplayName().Contains(Filter, ESearchCase::IgnoreCase))
				{
					Selected.Add(Info);
				}
			}

			if (Selected.Num() == 0)
			{
				return FMCPToolResult::ErrorStructured(EMCPError::NotFound,
					FString::Printf(TEXT("No automation tests match filter '%s'"), *Filter));
			}

			// Run each selected test synchronously through the framework's per-test path.
			// This is equivalent to the engine's "Automation RunTests <names>" but lets us
			// collect per-test outcomes inline.
			const double Started = FPlatformTime::Seconds();
			int32 Pass = 0, Fail = 0;
			TArray<TSharedPtr<FJsonValue>> Entries;

			for (const FAutomationTestInfo& Info : Selected)
			{
				const double TStart = FPlatformTime::Seconds();
				// StartTestByName expects the internal test name
				// ("<FSpecClass> <parameter>", from GetTestName), NOT the
				// beautified display name. It can also decline to start a test
				// (name not found, slow task or PIE in progress) — in that case
				// calling StopTest would trip check(GIsAutomationTesting) and
				// crash the editor, so only stop if a test actually started.
				Framework.StartTestByName(Info.GetTestName(), 0);
				FAutomationTestExecutionInfo ExecInfo;
				bool bOk = false;
				if (GIsAutomationTesting)
				{
					// Spec tests enqueue their It-blocks as latent commands;
					// they must be pumped to completion before StopTest, which
					// asserts on a non-empty latent queue. Commands that need
					// real engine ticks can't finish while we block the game
					// thread — drop them at the deadline rather than hanging.
					bool bPumpTimedOut = false;
					const double Deadline = Started + (double)Timeout;
					while (!Framework.ExecuteLatentCommands())
					{
						if (FPlatformTime::Seconds() > Deadline)
						{
							Framework.DequeueAllCommands();
							bPumpTimedOut = true;
							break;
						}
						FPlatformProcess::Sleep(0.001f);
					}

					bOk = Framework.StopTest(ExecInfo);

					if (bPumpTimedOut)
					{
						bOk = false;
						ExecInfo.AddEvent(FAutomationEvent(EAutomationEventType::Error,
							FString::Printf(TEXT("Test '%s' timed out while pumping latent commands; remaining commands were discarded"), *Info.GetTestName())));
					}
				}
				else
				{
					ExecInfo.AddEvent(FAutomationEvent(EAutomationEventType::Error,
						FString::Printf(TEXT("Test '%s' failed to start (not found, or a slow task/PIE session is in progress)"), *Info.GetTestName())));
				}

				const double TDur = FPlatformTime::Seconds() - TStart;
				if (bOk) ++Pass; else ++Fail;

				TSharedPtr<FJsonObject> E = MakeShared<FJsonObject>();
				E->SetStringField(TEXT("name"), Info.GetDisplayName());
				E->SetBoolField(TEXT("passed"), bOk);
				E->SetNumberField(TEXT("duration_sec"), TDur);

				TArray<TSharedPtr<FJsonValue>> Errors;
				for (const FAutomationExecutionEntry& Ent : ExecInfo.GetEntries())
				{
					if (Ent.Event.Type == EAutomationEventType::Error || Ent.Event.Type == EAutomationEventType::Warning)
					{
						Errors.Add(MakeShared<FJsonValueString>(Ent.Event.Message));
					}
				}
				if (Errors.Num() > 0) E->SetArrayField(TEXT("errors"), Errors);

				Entries.Add(MakeShared<FJsonValueObject>(E));

				// Honor timeout
				if (FPlatformTime::Seconds() - Started > (double)Timeout) break;
			}

			const double Total = FPlatformTime::Seconds() - Started;

			FLastReport& Last = GetLastReport();
			Last.bRan = true;
			Last.Filter = Filter;
			Last.NumPass = Pass;
			Last.NumFail = Fail;
			Last.DurationSeconds = Total;
			Last.Entries = Entries;

			TSharedPtr<FJsonObject> R = MakeShared<FJsonObject>();
			R->SetStringField(TEXT("filter"), Filter);
			R->SetNumberField(TEXT("pass"), Pass);
			R->SetNumberField(TEXT("fail"), Fail);
			R->SetNumberField(TEXT("duration_sec"), Total);
			R->SetNumberField(TEXT("ran"), Selected.Num());
			R->SetArrayField(TEXT("results"), Entries);

			return FMCPToolResult::SuccessStructured(
				FString::Printf(TEXT("Ran %d test(s): %d pass, %d fail in %.1fs"), Selected.Num(), Pass, Fail, Total), R);
		});

	// ================================================================
	// get_last_test_report
	// ================================================================
	MCP_TOOL(Registry, "get_last_test_report")
		.Description(TEXT(
			"Return the most recent run_automation_specs report. Returns ran=false if no run has occurred "
			"in this editor session."))
		.ReadOnly()
		.Idempotent()
		.Handle([](const TSharedPtr<FJsonObject>& Args) -> FMCPToolResult
		{
			BAIL_IF_INVALID(FMCPValidate::Args(Args));

			const FLastReport& Last = GetLastReport();
			TSharedPtr<FJsonObject> R = MakeShared<FJsonObject>();
			R->SetBoolField(TEXT("ran"), Last.bRan);
			if (!Last.bRan)
			{
				return FMCPToolResult::SuccessStructured(TEXT("No run yet"), R);
			}
			R->SetStringField(TEXT("filter"), Last.Filter);
			R->SetNumberField(TEXT("pass"), Last.NumPass);
			R->SetNumberField(TEXT("fail"), Last.NumFail);
			R->SetNumberField(TEXT("duration_sec"), Last.DurationSeconds);
			R->SetArrayField(TEXT("results"), Last.Entries);
			return FMCPToolResult::SuccessStructured(
				FString::Printf(TEXT("Last run: %d pass, %d fail (filter='%s')"),
					Last.NumPass, Last.NumFail, *Last.Filter), R);
		});

	// ================================================================
	// add_functional_test_actor
	// ================================================================
	MCP_TOOL(Registry, "add_functional_test_actor")
		.Description(TEXT(
			"Spawn an AFunctionalTest into the editor world at the given location. The placed actor "
			"can be configured in the Details panel and runs as part of any 'FunctionalTest' suite."))
		.RequiresPieOff()
		.StringArg(TEXT("name"), TEXT("Editor label for the new actor."), true)
		.NumberArg(TEXT("location_x"), TEXT("World location X (default 0)."))
		.NumberArg(TEXT("location_y"), TEXT("World location Y (default 0)."))
		.NumberArg(TEXT("location_z"), TEXT("World location Z (default 0)."))
		.Handle([](const TSharedPtr<FJsonObject>& Args) -> FMCPToolResult
		{
			BAIL_IF_INVALID(FMCPValidate::Args(Args));

			FString Name;
			BAIL_IF_INVALID(FMCPValidate::RequiredString(Args, TEXT("name"), Name));

			if (!GEditor)
			{
				return FMCPToolResult::ErrorStructured(EMCPError::Internal,
					TEXT("GEditor is not available"));
			}
			UWorld* World = GEditor->GetEditorWorldContext().World();
			if (!World)
			{
				return FMCPToolResult::ErrorStructured(EMCPError::Internal,
					TEXT("No editor world available"));
			}

			FVector Loc = FVector::ZeroVector;
			if (Args->HasField(TEXT("location_x"))) Loc.X = Args->GetNumberField(TEXT("location_x"));
			if (Args->HasField(TEXT("location_y"))) Loc.Y = Args->GetNumberField(TEXT("location_y"));
			if (Args->HasField(TEXT("location_z"))) Loc.Z = Args->GetNumberField(TEXT("location_z"));

			FActorSpawnParameters Params;
			Params.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
			AFunctionalTest* Actor = World->SpawnActor<AFunctionalTest>(AFunctionalTest::StaticClass(), Loc, FRotator::ZeroRotator, Params);
			if (!Actor)
			{
				return FMCPToolResult::ErrorStructured(EMCPError::Internal,
					TEXT("Failed to spawn AFunctionalTest"));
			}
			Actor->SetActorLabel(Name);

			TSharedPtr<FJsonObject> R = MakeShared<FJsonObject>();
			R->SetStringField(TEXT("name"), Actor->GetActorLabel());
			R->SetStringField(TEXT("path"), Actor->GetPathName());
			R->SetNumberField(TEXT("location_x"), Loc.X);
			R->SetNumberField(TEXT("location_y"), Loc.Y);
			R->SetNumberField(TEXT("location_z"), Loc.Z);
			return FMCPToolResult::SuccessStructured(
				FString::Printf(TEXT("Placed AFunctionalTest '%s'"), *Name), R);
		});
}

} // namespace MCPTestAuthoringTools
